[package]
name = "xelis-bytecode"
version = "0.1.0"
edition = "2021"

[dependencies]
xelis-types = { path = "../types" }
indexmap = "2.7.0"
thiserror = "1"
serde = { version = "1.0.215", features = ["derive"] }
hex = { version = "0.4.3", features = ["serde"] }

[dev-dependencies]
serde_json = "1"